gruppe.oid.skjermet=dbe4ad45-320b-4e9a-aaa1-73cca4ee124d
gruppe.oid.strengtfortrolig=a1b518e2-3947-478d-8929-e5d685c47cac
gruppe.oid.fortrolig=2e1dc582-f762-4510-a660-88bf68fb7128

pdl.pip.scope=api://dev-fss.pdl.pdl-pip-api/.default

skjermet.person.pip.base.url=https://skjermede-personer-pip.intern.dev.nav.no
skjermet.person.pip.scope=api://dev-gcp.nom.skjermede-personer-pip/.default
