# Jetty
server.port=8080
context.path=/fptilgang

ms.graph.url=https://graph.microsoft.com/v1.0
ms.graph.scopes=https://graph.microsoft.com/.default

redis.host=fpcache.teamforeldrepenger.svc.nais.local
redis.port=6379
