gruppe.oid.skjermet=e750ceb5-b70b-4d94-b4fa-9d22467b786b
gruppe.oid.strengtfortrolig=2931da41-8b8e-42cd-99c0-04a169ddae40
gruppe.oid.fortrolig=e98efc34-12d1-401f-b059-f17e62834065

pdl.pip.scope=api://prod-fss.pdl.pdl-pip-api/.default

skjermet.person.pip.base.url=https://skjermede-personer-pip.intern.nav.no
skjermet.person.pip.scope=api://prod-gcp.nom.skjermede-personer-pip/.default
