gruppe.oid.skjermet=dbe4ad45-320b-4e9a-aaa1-73cca4ee124d
gruppe.oid.strengtfortrolig=5ef775f2-61f8-4283-bf3d-8d03f428aa14
gruppe.oid.fortrolig=ea930b6b-9397-44d9-b9e6-f4cf527a632a

pdl.pip.scope=api://dev-fss:pdl:pdl-pip-api/.default

skjermet.person.pip.base.url=https://skjermede-personer-pip.intern.dev.nav.no
skjermet.person.pip.scope=api://dev-gcp.nom.skjermede-personer-pip/.default
