version: '3.7'
services:
  vtp-tilgang:
    image: vtp:lokal
    environment:
      TZ: Europe/Oslo
      NO_NAV_MODIG_SECURITY_APPCERT_KEYSTORE: /app/.modig/keystore.jks
      JAVAX_NET_SSL_TRUSTSTORE: /app/.modig/truststore.jks
    env_file:
      - "vtp.env"
    volumes:
      - "~/.modig:/app/.modig"
    ports:
      - "8060:8060"
      - "8063:8063"
      - "8636:8636"
      - "9093:9093"
      - "9092:9092"
      - "8389:8389"
    container_name: vtp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8060/rest/isReady"]
      interval: 30s
      timeout: 5s
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
