kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: fptilgang
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  image: {{image}}
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /fptilgang/internal/health/isAlive
    initialDelay: 2
    periodSeconds: 10
    failureThreshold: 20
    timeout: 3
  readiness:
    path: /fptilgang/internal/health/isReady
    initialDelay: 2
    periodSeconds: 10
    failureThreshold: 20
    timeout: 3
  startup:
    path: /fptilgang/internal/health/isReady
    initialDelay: 2
    periodSeconds: 10
    failureThreshold: 20
    timeout: 3
  preStopHook:
    http:
      path: /fptilgang/internal/health/preStop
  prometheus:
    enabled: true
    path: /fptilgang/internal/metrics/prometheus
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    scalingStrategy:
      cpu:
        thresholdPercentage: 40
      scaleUpStabilizationWindowSeconds: 20
  resources:
    limits:
      memory: "{{limits.mem}}"
    requests:
      cpu: "{{requests.cpu}}"
      memory: "{{requests.mem}}"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
        - id: "elastic-apm"
    logging:
      destinations:
        - id: loki
        - id: elastic
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "azp_name"
  envFrom:
    - secret: fpcache
  accessPolicy:
    inbound:
      rules:
        - application: fpsak
        - application: fplos
          namespace: teamforeldrepenger
          cluster: {{fss-cluster}}
        - application: fptilbake
        - application: fpformidling
          namespace: teamforeldrepenger
          cluster: {{fss-cluster}}
        - application: fpabakus
        - application: fpkalkulus
        - application: fprisk
        - application: fpoppdrag
        - application: fpsoknad
          namespace: teamforeldrepenger
          cluster: {{gcp-cluster}}
        - application: fpoversikt
          namespace: teamforeldrepenger
          cluster: {{gcp-cluster}}
        - application: fpinntektsmelding
          namespace: teamforeldrepenger
          cluster: {{gcp-cluster}}
        - application: fpmottak
          namespace: teamforeldrepenger
          cluster: {{gcp-cluster}}
        - application: fpformidling
          namespace: teamforeldrepenger
          cluster: {{gcp-cluster}}
        - application: fplos
          namespace: teamforeldrepenger
          cluster: {{gcp-cluster}}
